spring:
  jpa:
    hibernate:
      ddl-auto: update   # (create, update, validate, none)
    show-sql: true       # 실행되는 SQL을 콘솔에 출력
    properties:
      hibernate:
        format_sql: true # SQL을 보기 좋게 포맷팅
